// 더미 데이터: 실제 API 연동 시 삭제 예정

import type { Region, Template, GeneratedFile, Stats } from '@/types';

// 타입 re-export (기존 컴포넌트들의 import 경로 유지)
export type { Region, Template, GeneratedFile, Stats };

// 17개 광역자치단체 + 226개 시/군/구 (대한민국 전체)
export const dummyRegions: Region[] = [
  // 서울특별시 (25개 자치구)
  { id: 'seoul-1', name: '강남구', province: '서울특별시', district: '강남구' },
  { id: 'seoul-2', name: '강동구', province: '서울특별시', district: '강동구' },
  { id: 'seoul-3', name: '강북구', province: '서울특별시', district: '강북구' },
  { id: 'seoul-4', name: '강서구', province: '서울특별시', district: '강서구' },
  { id: 'seoul-5', name: '관악구', province: '서울특별시', district: '관악구' },
  { id: 'seoul-6', name: '광진구', province: '서울특별시', district: '광진구' },
  { id: 'seoul-7', name: '구로구', province: '서울특별시', district: '구로구' },
  { id: 'seoul-8', name: '금천구', province: '서울특별시', district: '금천구' },
  { id: 'seoul-9', name: '노원구', province: '서울특별시', district: '노원구' },
  { id: 'seoul-10', name: '도봉구', province: '서울특별시', district: '도봉구' },
  { id: 'seoul-11', name: '동대문구', province: '서울특별시', district: '동대문구' },
  { id: 'seoul-12', name: '동작구', province: '서울특별시', district: '동작구' },
  { id: 'seoul-13', name: '마포구', province: '서울특별시', district: '마포구' },
  { id: 'seoul-14', name: '서대문구', province: '서울특별시', district: '서대문구' },
  { id: 'seoul-15', name: '서초구', province: '서울특별시', district: '서초구' },
  { id: 'seoul-16', name: '성동구', province: '서울특별시', district: '성동구' },
  { id: 'seoul-17', name: '성북구', province: '서울특별시', district: '성북구' },
  { id: 'seoul-18', name: '송파구', province: '서울특별시', district: '송파구' },
  { id: 'seoul-19', name: '양천구', province: '서울특별시', district: '양천구' },
  { id: 'seoul-20', name: '영등포구', province: '서울특별시', district: '영등포구' },
  { id: 'seoul-21', name: '용산구', province: '서울특별시', district: '용산구' },
  { id: 'seoul-22', name: '은평구', province: '서울특별시', district: '은평구' },
  { id: 'seoul-23', name: '종로구', province: '서울특별시', district: '종로구' },
  { id: 'seoul-24', name: '중구', province: '서울특별시', district: '중구' },
  { id: 'seoul-25', name: '중랑구', province: '서울특별시', district: '중랑구' },

  // 부산광역시 (16개 구/군)
  { id: 'busan-1', name: '강서구', province: '부산광역시', district: '강서구' },
  { id: 'busan-2', name: '금정구', province: '부산광역시', district: '금정구' },
  { id: 'busan-3', name: '기장군', province: '부산광역시', district: '기장군' },
  { id: 'busan-4', name: '남구', province: '부산광역시', district: '남구' },
  { id: 'busan-5', name: '동구', province: '부산광역시', district: '동구' },
  { id: 'busan-6', name: '동래구', province: '부산광역시', district: '동래구' },
  { id: 'busan-7', name: '부산진구', province: '부산광역시', district: '부산진구' },
  { id: 'busan-8', name: '북구', province: '부산광역시', district: '북구' },
  { id: 'busan-9', name: '사상구', province: '부산광역시', district: '사상구' },
  { id: 'busan-10', name: '사하구', province: '부산광역시', district: '사하구' },
  { id: 'busan-11', name: '서구', province: '부산광역시', district: '서구' },
  { id: 'busan-12', name: '수영구', province: '부산광역시', district: '수영구' },
  { id: 'busan-13', name: '연제구', province: '부산광역시', district: '연제구' },
  { id: 'busan-14', name: '영도구', province: '부산광역시', district: '영도구' },
  { id: 'busan-15', name: '중구', province: '부산광역시', district: '중구' },
  { id: 'busan-16', name: '해운대구', province: '부산광역시', district: '해운대구' },

  // 대구광역시 (8개 구/군)
  { id: 'daegu-1', name: '남구', province: '대구광역시', district: '남구' },
  { id: 'daegu-2', name: '달서구', province: '대구광역시', district: '달서구' },
  { id: 'daegu-3', name: '달성군', province: '대구광역시', district: '달성군' },
  { id: 'daegu-4', name: '동구', province: '대구광역시', district: '동구' },
  { id: 'daegu-5', name: '북구', province: '대구광역시', district: '북구' },
  { id: 'daegu-6', name: '서구', province: '대구광역시', district: '서구' },
  { id: 'daegu-7', name: '수성구', province: '대구광역시', district: '수성구' },
  { id: 'daegu-8', name: '중구', province: '대구광역시', district: '중구' },

  // 인천광역시 (10개 구/군)
  { id: 'incheon-1', name: '강화군', province: '인천광역시', district: '강화군' },
  { id: 'incheon-2', name: '계양구', province: '인천광역시', district: '계양구' },
  { id: 'incheon-3', name: '남동구', province: '인천광역시', district: '남동구' },
  { id: 'incheon-4', name: '동구', province: '인천광역시', district: '동구' },
  { id: 'incheon-5', name: '미추홀구', province: '인천광역시', district: '미추홀구' },
  { id: 'incheon-6', name: '부평구', province: '인천광역시', district: '부평구' },
  { id: 'incheon-7', name: '서구', province: '인천광역시', district: '서구' },
  { id: 'incheon-8', name: '연수구', province: '인천광역시', district: '연수구' },
  { id: 'incheon-9', name: '옹진군', province: '인천광역시', district: '옹진군' },
  { id: 'incheon-10', name: '중구', province: '인천광역시', district: '중구' },

  // 광주광역시 (5개 구)
  { id: 'gwangju-1', name: '광산구', province: '광주광역시', district: '광산구' },
  { id: 'gwangju-2', name: '남구', province: '광주광역시', district: '남구' },
  { id: 'gwangju-3', name: '동구', province: '광주광역시', district: '동구' },
  { id: 'gwangju-4', name: '북구', province: '광주광역시', district: '북구' },
  { id: 'gwangju-5', name: '서구', province: '광주광역시', district: '서구' },

  // 대전광역시 (5개 구)
  { id: 'daejeon-1', name: '대덕구', province: '대전광역시', district: '대덕구' },
  { id: 'daejeon-2', name: '동구', province: '대전광역시', district: '동구' },
  { id: 'daejeon-3', name: '서구', province: '대전광역시', district: '서구' },
  { id: 'daejeon-4', name: '유성구', province: '대전광역시', district: '유성구' },
  { id: 'daejeon-5', name: '중구', province: '대전광역시', district: '중구' },

  // 울산광역시 (5개 구/군)
  { id: 'ulsan-1', name: '남구', province: '울산광역시', district: '남구' },
  { id: 'ulsan-2', name: '동구', province: '울산광역시', district: '동구' },
  { id: 'ulsan-3', name: '북구', province: '울산광역시', district: '북구' },
  { id: 'ulsan-4', name: '울주군', province: '울산광역시', district: '울주군' },
  { id: 'ulsan-5', name: '중구', province: '울산광역시', district: '중구' },

  // 세종특별자치시 (1개)
  { id: 'sejong-1', name: '세종시', province: '세종특별자치시', district: '세종시' },

  // 경기도 (31개 시/군)
  { id: 'gyeonggi-1', name: '가평군', province: '경기도', district: '가평군' },
  { id: 'gyeonggi-2', name: '고양시', province: '경기도', district: '고양시' },
  { id: 'gyeonggi-3', name: '과천시', province: '경기도', district: '과천시' },
  { id: 'gyeonggi-4', name: '광명시', province: '경기도', district: '광명시' },
  { id: 'gyeonggi-5', name: '광주시', province: '경기도', district: '광주시' },
  { id: 'gyeonggi-6', name: '구리시', province: '경기도', district: '구리시' },
  { id: 'gyeonggi-7', name: '군포시', province: '경기도', district: '군포시' },
  { id: 'gyeonggi-8', name: '김포시', province: '경기도', district: '김포시' },
  { id: 'gyeonggi-9', name: '남양주시', province: '경기도', district: '남양주시' },
  { id: 'gyeonggi-10', name: '동두천시', province: '경기도', district: '동두천시' },
  { id: 'gyeonggi-11', name: '부천시', province: '경기도', district: '부천시' },
  { id: 'gyeonggi-12', name: '성남시', province: '경기도', district: '성남시' },
  { id: 'gyeonggi-13', name: '수원시', province: '경기도', district: '수원시' },
  { id: 'gyeonggi-14', name: '시흥시', province: '경기도', district: '시흥시' },
  { id: 'gyeonggi-15', name: '안산시', province: '경기도', district: '안산시' },
  { id: 'gyeonggi-16', name: '안성시', province: '경기도', district: '안성시' },
  { id: 'gyeonggi-17', name: '안양시', province: '경기도', district: '안양시' },
  { id: 'gyeonggi-18', name: '양주시', province: '경기도', district: '양주시' },
  { id: 'gyeonggi-19', name: '양평군', province: '경기도', district: '양평군' },
  { id: 'gyeonggi-20', name: '여주시', province: '경기도', district: '여주시' },
  { id: 'gyeonggi-21', name: '연천군', province: '경기도', district: '연천군' },
  { id: 'gyeonggi-22', name: '오산시', province: '경기도', district: '오산시' },
  { id: 'gyeonggi-23', name: '용인시', province: '경기도', district: '용인시' },
  { id: 'gyeonggi-24', name: '의왕시', province: '경기도', district: '의왕시' },
  { id: 'gyeonggi-25', name: '의정부시', province: '경기도', district: '의정부시' },
  { id: 'gyeonggi-26', name: '이천시', province: '경기도', district: '이천시' },
  { id: 'gyeonggi-27', name: '파주시', province: '경기도', district: '파주시' },
  { id: 'gyeonggi-28', name: '평택시', province: '경기도', district: '평택시' },
  { id: 'gyeonggi-29', name: '포천시', province: '경기도', district: '포천시' },
  { id: 'gyeonggi-30', name: '하남시', province: '경기도', district: '하남시' },
  { id: 'gyeonggi-31', name: '화성시', province: '경기도', district: '화성시' },

  // 강원특별자치도 (18개 시/군)
  { id: 'gangwon-1', name: '강릉시', province: '강원특별자치도', district: '강릉시' },
  { id: 'gangwon-2', name: '고성군', province: '강원특별자치도', district: '고성군' },
  { id: 'gangwon-3', name: '동해시', province: '강원특별자치도', district: '동해시' },
  { id: 'gangwon-4', name: '삼척시', province: '강원특별자치도', district: '삼척시' },
  { id: 'gangwon-5', name: '속초시', province: '강원특별자치도', district: '속초시' },
  { id: 'gangwon-6', name: '양구군', province: '강원특별자치도', district: '양구군' },
  { id: 'gangwon-7', name: '양양군', province: '강원특별자치도', district: '양양군' },
  { id: 'gangwon-8', name: '영월군', province: '강원특별자치도', district: '영월군' },
  { id: 'gangwon-9', name: '원주시', province: '강원특별자치도', district: '원주시' },
  { id: 'gangwon-10', name: '인제군', province: '강원특별자치도', district: '인제군' },
  { id: 'gangwon-11', name: '정선군', province: '강원특별자치도', district: '정선군' },
  { id: 'gangwon-12', name: '철원군', province: '강원특별자치도', district: '철원군' },
  { id: 'gangwon-13', name: '춘천시', province: '강원특별자치도', district: '춘천시' },
  { id: 'gangwon-14', name: '태백시', province: '강원특별자치도', district: '태백시' },
  { id: 'gangwon-15', name: '평창군', province: '강원특별자치도', district: '평창군' },
  { id: 'gangwon-16', name: '홍천군', province: '강원특별자치도', district: '홍천군' },
  { id: 'gangwon-17', name: '화천군', province: '강원특별자치도', district: '화천군' },
  { id: 'gangwon-18', name: '횡성군', province: '강원특별자치도', district: '횡성군' },

  // 충청북도 (11개 시/군)
  { id: 'chungbuk-1', name: '괴산군', province: '충청북도', district: '괴산군' },
  { id: 'chungbuk-2', name: '단양군', province: '충청북도', district: '단양군' },
  { id: 'chungbuk-3', name: '보은군', province: '충청북도', district: '보은군' },
  { id: 'chungbuk-4', name: '영동군', province: '충청북도', district: '영동군' },
  { id: 'chungbuk-5', name: '옥천군', province: '충청북도', district: '옥천군' },
  { id: 'chungbuk-6', name: '음성군', province: '충청북도', district: '음성군' },
  { id: 'chungbuk-7', name: '제천시', province: '충청북도', district: '제천시' },
  { id: 'chungbuk-8', name: '증평군', province: '충청북도', district: '증평군' },
  { id: 'chungbuk-9', name: '진천군', province: '충청북도', district: '진천군' },
  { id: 'chungbuk-10', name: '청주시', province: '충청북도', district: '청주시' },
  { id: 'chungbuk-11', name: '충주시', province: '충청북도', district: '충주시' },

  // 충청남도 (15개 시/군)
  { id: 'chungnam-1', name: '계룡시', province: '충청남도', district: '계룡시' },
  { id: 'chungnam-2', name: '공주시', province: '충청남도', district: '공주시' },
  { id: 'chungnam-3', name: '금산군', province: '충청남도', district: '금산군' },
  { id: 'chungnam-4', name: '논산시', province: '충청남도', district: '논산시' },
  { id: 'chungnam-5', name: '당진시', province: '충청남도', district: '당진시' },
  { id: 'chungnam-6', name: '보령시', province: '충청남도', district: '보령시' },
  { id: 'chungnam-7', name: '부여군', province: '충청남도', district: '부여군' },
  { id: 'chungnam-8', name: '서산시', province: '충청남도', district: '서산시' },
  { id: 'chungnam-9', name: '서천군', province: '충청남도', district: '서천군' },
  { id: 'chungnam-10', name: '아산시', province: '충청남도', district: '아산시' },
  { id: 'chungnam-11', name: '예산군', province: '충청남도', district: '예산군' },
  { id: 'chungnam-12', name: '천안시', province: '충청남도', district: '천안시' },
  { id: 'chungnam-13', name: '청양군', province: '충청남도', district: '청양군' },
  { id: 'chungnam-14', name: '태안군', province: '충청남도', district: '태안군' },
  { id: 'chungnam-15', name: '홍성군', province: '충청남도', district: '홍성군' },

  // 전북특별자치도 (14개 시/군)
  { id: 'jeonbuk-1', name: '고창군', province: '전북특별자치도', district: '고창군' },
  { id: 'jeonbuk-2', name: '군산시', province: '전북특별자치도', district: '군산시' },
  { id: 'jeonbuk-3', name: '김제시', province: '전북특별자치도', district: '김제시' },
  { id: 'jeonbuk-4', name: '남원시', province: '전북특별자치도', district: '남원시' },
  { id: 'jeonbuk-5', name: '무주군', province: '전북특별자치도', district: '무주군' },
  { id: 'jeonbuk-6', name: '부안군', province: '전북특별자치도', district: '부안군' },
  { id: 'jeonbuk-7', name: '순창군', province: '전북특별자치도', district: '순창군' },
  { id: 'jeonbuk-8', name: '완주군', province: '전북특별자치도', district: '완주군' },
  { id: 'jeonbuk-9', name: '익산시', province: '전북특별자치도', district: '익산시' },
  { id: 'jeonbuk-10', name: '임실군', province: '전북특별자치도', district: '임실군' },
  { id: 'jeonbuk-11', name: '장수군', province: '전북특별자치도', district: '장수군' },
  { id: 'jeonbuk-12', name: '전주시', province: '전북특별자치도', district: '전주시' },
  { id: 'jeonbuk-13', name: '정읍시', province: '전북특별자치도', district: '정읍시' },
  { id: 'jeonbuk-14', name: '진안군', province: '전북특별자치도', district: '진안군' },

  // 전라남도 (22개 시/군)
  { id: 'jeonnam-1', name: '강진군', province: '전라남도', district: '강진군' },
  { id: 'jeonnam-2', name: '고흥군', province: '전라남도', district: '고흥군' },
  { id: 'jeonnam-3', name: '곡성군', province: '전라남도', district: '곡성군' },
  { id: 'jeonnam-4', name: '광양시', province: '전라남도', district: '광양시' },
  { id: 'jeonnam-5', name: '구례군', province: '전라남도', district: '구례군' },
  { id: 'jeonnam-6', name: '나주시', province: '전라남도', district: '나주시' },
  { id: 'jeonnam-7', name: '담양군', province: '전라남도', district: '담양군' },
  { id: 'jeonnam-8', name: '목포시', province: '전라남도', district: '목포시' },
  { id: 'jeonnam-9', name: '무안군', province: '전라남도', district: '무안군' },
  { id: 'jeonnam-10', name: '보성군', province: '전라남도', district: '보성군' },
  { id: 'jeonnam-11', name: '순천시', province: '전라남도', district: '순천시' },
  { id: 'jeonnam-12', name: '신안군', province: '전라남도', district: '신안군' },
  { id: 'jeonnam-13', name: '여수시', province: '전라남도', district: '여수시' },
  { id: 'jeonnam-14', name: '영광군', province: '전라남도', district: '영광군' },
  { id: 'jeonnam-15', name: '영암군', province: '전라남도', district: '영암군' },
  { id: 'jeonnam-16', name: '완도군', province: '전라남도', district: '완도군' },
  { id: 'jeonnam-17', name: '장성군', province: '전라남도', district: '장성군' },
  { id: 'jeonnam-18', name: '장흥군', province: '전라남도', district: '장흥군' },
  { id: 'jeonnam-19', name: '진도군', province: '전라남도', district: '진도군' },
  { id: 'jeonnam-20', name: '함평군', province: '전라남도', district: '함평군' },
  { id: 'jeonnam-21', name: '해남군', province: '전라남도', district: '해남군' },
  { id: 'jeonnam-22', name: '화순군', province: '전라남도', district: '화순군' },

  // 경상북도 (23개 시/군)
  { id: 'gyeongbuk-1', name: '경산시', province: '경상북도', district: '경산시' },
  { id: 'gyeongbuk-2', name: '경주시', province: '경상북도', district: '경주시' },
  { id: 'gyeongbuk-3', name: '고령군', province: '경상북도', district: '고령군' },
  { id: 'gyeongbuk-4', name: '구미시', province: '경상북도', district: '구미시' },
  { id: 'gyeongbuk-5', name: '군위군', province: '경상북도', district: '군위군' },
  { id: 'gyeongbuk-6', name: '김천시', province: '경상북도', district: '김천시' },
  { id: 'gyeongbuk-7', name: '문경시', province: '경상북도', district: '문경시' },
  { id: 'gyeongbuk-8', name: '봉화군', province: '경상북도', district: '봉화군' },
  { id: 'gyeongbuk-9', name: '상주시', province: '경상북도', district: '상주시' },
  { id: 'gyeongbuk-10', name: '성주군', province: '경상북도', district: '성주군' },
  { id: 'gyeongbuk-11', name: '안동시', province: '경상북도', district: '안동시' },
  { id: 'gyeongbuk-12', name: '영덕군', province: '경상북도', district: '영덕군' },
  { id: 'gyeongbuk-13', name: '영양군', province: '경상북도', district: '영양군' },
  { id: 'gyeongbuk-14', name: '영주시', province: '경상북도', district: '영주시' },
  { id: 'gyeongbuk-15', name: '영천시', province: '경상북도', district: '영천시' },
  { id: 'gyeongbuk-16', name: '예천군', province: '경상북도', district: '예천군' },
  { id: 'gyeongbuk-17', name: '울릉군', province: '경상북도', district: '울릉군' },
  { id: 'gyeongbuk-18', name: '울진군', province: '경상북도', district: '울진군' },
  { id: 'gyeongbuk-19', name: '의성군', province: '경상북도', district: '의성군' },
  { id: 'gyeongbuk-20', name: '청도군', province: '경상북도', district: '청도군' },
  { id: 'gyeongbuk-21', name: '청송군', province: '경상북도', district: '청송군' },
  { id: 'gyeongbuk-22', name: '칠곡군', province: '경상북도', district: '칠곡군' },
  { id: 'gyeongbuk-23', name: '포항시', province: '경상북도', district: '포항시' },

  // 경상남도 (18개 시/군)
  { id: 'gyeongnam-1', name: '거제시', province: '경상남도', district: '거제시' },
  { id: 'gyeongnam-2', name: '거창군', province: '경상남도', district: '거창군' },
  { id: 'gyeongnam-3', name: '고성군', province: '경상남도', district: '고성군' },
  { id: 'gyeongnam-4', name: '김해시', province: '경상남도', district: '김해시' },
  { id: 'gyeongnam-5', name: '남해군', province: '경상남도', district: '남해군' },
  { id: 'gyeongnam-6', name: '밀양시', province: '경상남도', district: '밀양시' },
  { id: 'gyeongnam-7', name: '사천시', province: '경상남도', district: '사천시' },
  { id: 'gyeongnam-8', name: '산청군', province: '경상남도', district: '산청군' },
  { id: 'gyeongnam-9', name: '양산시', province: '경상남도', district: '양산시' },
  { id: 'gyeongnam-10', name: '의령군', province: '경상남도', district: '의령군' },
  { id: 'gyeongnam-11', name: '진주시', province: '경상남도', district: '진주시' },
  { id: 'gyeongnam-12', name: '창녕군', province: '경상남도', district: '창녕군' },
  { id: 'gyeongnam-13', name: '창원시', province: '경상남도', district: '창원시' },
  { id: 'gyeongnam-14', name: '통영시', province: '경상남도', district: '통영시' },
  { id: 'gyeongnam-15', name: '하동군', province: '경상남도', district: '하동군' },
  { id: 'gyeongnam-16', name: '함안군', province: '경상남도', district: '함안군' },
  { id: 'gyeongnam-17', name: '함양군', province: '경상남도', district: '함양군' },
  { id: 'gyeongnam-18', name: '합천군', province: '경상남도', district: '합천군' },

  // 제주특별자치도 (2개 시)
  { id: 'jeju-1', name: '서귀포시', province: '제주특별자치도', district: '서귀포시' },
  { id: 'jeju-2', name: '제주시', province: '제주특별자치도', district: '제주시' },
];

// 더미 템플릿 데이터
export const dummyTemplates: Template[] = [
  {
    id: 't1',
    title: '우리 고장의 모습 - 기본형',
    description: '3학년 1학기 사회 교과서 기본 템플릿입니다.',
    version: '1.0',
    thumbnailUrl: '/placeholder-template.png',
    createdAt: '2025-01-15',
    // Phase 3: 확장된 필드
    variables: [
      { key: '{{지역명}}', label: '지역명', description: '선택한 지역의 이름' },
      { key: '{{학교명}}', label: '학교명', description: '자동 설정 (기본값: "수업자료")' },
      { key: '{{날짜}}', label: '날짜', description: '자료 생성 날짜' },
    ],
    slideCount: 15,
    fileSize: '2.3MB',
    category: '기본',
    tags: ['3학년', '1학기', '우리고장'],
    isActive: true,
    previewImageUrl: '/placeholder-preview.png',
    usageGuide: '기본적인 우리 고장 소개 수업에 적합합니다. 지역의 위치, 특징, 주요 장소를 다룹니다.',
    versionHistory: [
      {
        version: '1.0',
        date: '2025-01-15',
        changes: ['초기 버전 생성', '기본 슬라이드 15장 구성'],
      },
    ],
  },
  {
    id: 't2',
    title: '우리 고장의 생활 - 심화형',
    description: '사진과 지도가 풍부한 심화 템플릿입니다.',
    version: '2.1',
    thumbnailUrl: '/placeholder-template.png',
    createdAt: '2025-02-10',
    // Phase 3: 확장된 필드
    variables: [
      { key: '{{지역명}}', label: '지역명', description: '선택한 지역의 이름' },
      { key: '{{학교명}}', label: '학교명', description: '자동 설정 (기본값: "수업자료")' },
      { key: '{{날짜}}', label: '날짜', description: '자료 생성 날짜' },
      { key: '{{인구수}}', label: '인구수', description: '지역 인구 통계' },
    ],
    slideCount: 25,
    fileSize: '4.7MB',
    category: '심화',
    tags: ['3학년', '2학기', '생활모습', '심화학습'],
    isActive: true,
    previewImageUrl: '/placeholder-preview.png',
    usageGuide: '우리 고장의 생활 모습을 심도있게 다루는 템플릿입니다. 사진과 지도 자료가 풍부합니다.',
    versionHistory: [
      {
        version: '2.1',
        date: '2025-02-10',
        changes: ['지도 자료 업데이트', '슬라이드 레이아웃 개선'],
      },
      {
        version: '2.0',
        date: '2025-01-20',
        changes: ['사진 자료 추가', '슬라이드 5장 추가'],
      },
      {
        version: '1.0',
        date: '2024-12-01',
        changes: ['초기 버전 생성'],
      },
    ],
  },
  {
    id: 't3',
    title: '지역 특산물과 산업',
    description: '지역 경제와 특산물을 다루는 템플릿입니다.',
    version: '1.5',
    thumbnailUrl: '/placeholder-template.png',
    createdAt: '2025-03-05',
    // Phase 3: 확장된 필드
    variables: [
      { key: '{{지역명}}', label: '지역명', description: '선택한 지역의 이름' },
      { key: '{{특산물}}', label: '특산물', description: '지역 대표 특산물' },
      { key: '{{주요산업}}', label: '주요산업', description: '지역의 주요 산업' },
    ],
    slideCount: 18,
    fileSize: '3.1MB',
    category: '특화',
    tags: ['3학년', '경제', '특산물', '산업'],
    isActive: true,
    previewImageUrl: '/placeholder-preview.png',
    usageGuide: '지역의 경제 활동과 특산물을 소개하는 수업에 활용하세요.',
    versionHistory: [
      {
        version: '1.5',
        date: '2025-03-05',
        changes: ['특산물 이미지 품질 개선', '차트 디자인 업데이트'],
      },
      {
        version: '1.0',
        date: '2025-02-15',
        changes: ['초기 버전 생성'],
      },
    ],
  },
  {
    id: 't4',
    title: '우리 고장의 역사',
    description: '지역의 역사와 문화유산을 다루는 템플릿입니다.',
    version: '1.0',
    thumbnailUrl: '/placeholder-template.png',
    createdAt: '2025-03-20',
    // Phase 3: 확장된 필드
    variables: [
      { key: '{{지역명}}', label: '지역명', description: '선택한 지역의 이름' },
      { key: '{{문화재}}', label: '문화재', description: '지역의 주요 문화재' },
      { key: '{{역사인물}}', label: '역사인물', description: '지역 출신 역사 인물' },
    ],
    slideCount: 20,
    fileSize: '3.8MB',
    category: '특화',
    tags: ['3학년', '역사', '문화재'],
    isActive: false,
    previewImageUrl: '/placeholder-preview.png',
    usageGuide: '지역의 역사와 문화유산을 학습하는 수업에 적합합니다.',
    versionHistory: [
      {
        version: '1.0',
        date: '2025-03-20',
        changes: ['초기 버전 생성', '역사 타임라인 슬라이드 추가'],
      },
    ],
  },
];

// 더미 생성 파일 목록
export const dummyGeneratedFiles: GeneratedFile[] = [
  {
    id: 'g1',
    regionName: '강남구',
    templateTitle: '우리 고장의 모습 - 기본형',
    generatedAt: '2025-10-28 14:35',
    status: 'completed',
    downloadUrl: '/download/g1.pptx',
  },
  {
    id: 'g2',
    regionName: '해운대구',
    templateTitle: '우리 고장의 생활 - 심화형',
    generatedAt: '2025-10-27 09:20',
    status: 'completed',
    downloadUrl: '/download/g2.pptx',
  },
  {
    id: 'g3',
    regionName: '수성구',
    templateTitle: '지역 특산물과 산업',
    generatedAt: '2025-10-26 16:50',
    status: 'processing',
  },
  {
    id: 'g4',
    regionName: '유성구',
    templateTitle: '우리 고장의 모습 - 기본형',
    generatedAt: '2025-10-25 11:10',
    status: 'failed',
  },
];

// 더미 통계 데이터
export const dummyStats: Stats = {
  totalGenerations: 3247,
  totalUsers: 542,
  averageGenerationTime: '1분 45초',
  popularRegions: [
    { name: '강남구', count: 235 },
    { name: '해운대구', count: 198 },
    { name: '수성구', count: 175 },
    { name: '유성구', count: 142 },
    { name: '남동구', count: 128 },
  ],
};
