/**
 * 한국관광공사 API 전체 지역 코드 매핑
 * 17개 시도 + 226개 시군구
 *
 * 출처: 한국관광공사 Tour API 4.0
 * https://www.data.go.kr/data/15101578/openapi.do
 */

export interface AreaCode {
  areaCode: string;
  sigunguCode?: string;
}

export const KOREA_AREA_CODES: Record<string, AreaCode> = {
  // ===== 서울특별시 (1) =====
  '서울특별시': { areaCode: '1' },
  '서울': { areaCode: '1' },
  '서울특별시 강남구': { areaCode: '1', sigunguCode: '1' },
  '서울특별시 강동구': { areaCode: '1', sigunguCode: '2' },
  '서울특별시 강북구': { areaCode: '1', sigunguCode: '3' },
  '서울특별시 강서구': { areaCode: '1', sigunguCode: '4' },
  '서울특별시 관악구': { areaCode: '1', sigunguCode: '5' },
  '서울특별시 광진구': { areaCode: '1', sigunguCode: '6' },
  '서울특별시 구로구': { areaCode: '1', sigunguCode: '7' },
  '서울특별시 금천구': { areaCode: '1', sigunguCode: '8' },
  '서울특별시 노원구': { areaCode: '1', sigunguCode: '9' },
  '서울특별시 도봉구': { areaCode: '1', sigunguCode: '10' },
  '서울특별시 동대문구': { areaCode: '1', sigunguCode: '11' },
  '서울특별시 동작구': { areaCode: '1', sigunguCode: '12' },
  '서울특별시 마포구': { areaCode: '1', sigunguCode: '13' },
  '서울특별시 서대문구': { areaCode: '1', sigunguCode: '14' },
  '서울특별시 서초구': { areaCode: '1', sigunguCode: '15' },
  '서울특별시 성동구': { areaCode: '1', sigunguCode: '16' },
  '서울특별시 성북구': { areaCode: '1', sigunguCode: '17' },
  '서울특별시 송파구': { areaCode: '1', sigunguCode: '18' },
  '서울특별시 양천구': { areaCode: '1', sigunguCode: '19' },
  '서울특별시 영등포구': { areaCode: '1', sigunguCode: '20' },
  '서울특별시 용산구': { areaCode: '1', sigunguCode: '21' },
  '서울특별시 은평구': { areaCode: '1', sigunguCode: '22' },
  '서울특별시 종로구': { areaCode: '1', sigunguCode: '23' },
  '서울특별시 중구': { areaCode: '1', sigunguCode: '24' },
  '서울특별시 중랑구': { areaCode: '1', sigunguCode: '25' },

  // ===== 인천광역시 (2) =====
  '인천광역시': { areaCode: '2' },
  '인천': { areaCode: '2' },
  '인천광역시 강화군': { areaCode: '2', sigunguCode: '1' },
  '인천광역시 계양구': { areaCode: '2', sigunguCode: '2' },
  '인천광역시 남동구': { areaCode: '2', sigunguCode: '3' },
  '인천광역시 동구': { areaCode: '2', sigunguCode: '4' },
  '인천광역시 미추홀구': { areaCode: '2', sigunguCode: '5' },
  '인천광역시 부평구': { areaCode: '2', sigunguCode: '6' },
  '인천광역시 서구': { areaCode: '2', sigunguCode: '7' },
  '인천광역시 연수구': { areaCode: '2', sigunguCode: '8' },
  '인천광역시 옹진군': { areaCode: '2', sigunguCode: '9' },
  '인천광역시 중구': { areaCode: '2', sigunguCode: '10' },

  // ===== 대전광역시 (3) =====
  '대전광역시': { areaCode: '3' },
  '대전': { areaCode: '3' },
  '대전광역시 대덕구': { areaCode: '3', sigunguCode: '1' },
  '대전광역시 동구': { areaCode: '3', sigunguCode: '2' },
  '대전광역시 서구': { areaCode: '3', sigunguCode: '3' },
  '대전광역시 유성구': { areaCode: '3', sigunguCode: '4' },
  '대전광역시 중구': { areaCode: '3', sigunguCode: '5' },

  // ===== 대구광역시 (4) =====
  '대구광역시': { areaCode: '4' },
  '대구': { areaCode: '4' },
  '대구광역시 남구': { areaCode: '4', sigunguCode: '1' },
  '대구광역시 달서구': { areaCode: '4', sigunguCode: '2' },
  '대구광역시 달성군': { areaCode: '4', sigunguCode: '3' },
  '대구광역시 동구': { areaCode: '4', sigunguCode: '4' },
  '대구광역시 북구': { areaCode: '4', sigunguCode: '5' },
  '대구광역시 서구': { areaCode: '4', sigunguCode: '6' },
  '대구광역시 수성구': { areaCode: '4', sigunguCode: '7' },
  '대구광역시 중구': { areaCode: '4', sigunguCode: '8' },
  '대구광역시 군위군': { areaCode: '4', sigunguCode: '9' },

  // ===== 광주광역시 (5) =====
  '광주광역시': { areaCode: '5' },
  '광주': { areaCode: '5' },
  '광주광역시 광산구': { areaCode: '5', sigunguCode: '1' },
  '광주광역시 남구': { areaCode: '5', sigunguCode: '2' },
  '광주광역시 동구': { areaCode: '5', sigunguCode: '3' },
  '광주광역시 북구': { areaCode: '5', sigunguCode: '4' },
  '광주광역시 서구': { areaCode: '5', sigunguCode: '5' },

  // ===== 부산광역시 (6) =====
  '부산광역시': { areaCode: '6' },
  '부산': { areaCode: '6' },
  '부산광역시 강서구': { areaCode: '6', sigunguCode: '1' },
  '부산광역시 금정구': { areaCode: '6', sigunguCode: '2' },
  '부산광역시 기장군': { areaCode: '6', sigunguCode: '3' },
  '부산광역시 남구': { areaCode: '6', sigunguCode: '4' },
  '부산광역시 동구': { areaCode: '6', sigunguCode: '5' },
  '부산광역시 동래구': { areaCode: '6', sigunguCode: '6' },
  '부산광역시 부산진구': { areaCode: '6', sigunguCode: '7' },
  '부산광역시 북구': { areaCode: '6', sigunguCode: '8' },
  '부산광역시 사상구': { areaCode: '6', sigunguCode: '9' },
  '부산광역시 사하구': { areaCode: '6', sigunguCode: '10' },
  '부산광역시 서구': { areaCode: '6', sigunguCode: '11' },
  '부산광역시 수영구': { areaCode: '6', sigunguCode: '12' },
  '부산광역시 연제구': { areaCode: '6', sigunguCode: '13' },
  '부산광역시 영도구': { areaCode: '6', sigunguCode: '14' },
  '부산광역시 중구': { areaCode: '6', sigunguCode: '15' },
  '부산광역시 해운대구': { areaCode: '6', sigunguCode: '16' },

  // ===== 울산광역시 (7) =====
  '울산광역시': { areaCode: '7' },
  '울산': { areaCode: '7' },
  '울산광역시 남구': { areaCode: '7', sigunguCode: '1' },
  '울산광역시 동구': { areaCode: '7', sigunguCode: '2' },
  '울산광역시 북구': { areaCode: '7', sigunguCode: '3' },
  '울산광역시 울주군': { areaCode: '7', sigunguCode: '4' },
  '울산광역시 중구': { areaCode: '7', sigunguCode: '5' },

  // ===== 세종특별자치시 (8) =====
  '세종특별자치시': { areaCode: '8' },
  '세종': { areaCode: '8' },

  // ===== 경기도 (31) =====
  '경기도': { areaCode: '31' },
  '경기': { areaCode: '31' },
  '경기도 가평군': { areaCode: '31', sigunguCode: '1' },
  '가평군': { areaCode: '31', sigunguCode: '1' },
  '경기도 고양시': { areaCode: '31', sigunguCode: '2' },
  '고양시': { areaCode: '31', sigunguCode: '2' },
  '경기도 과천시': { areaCode: '31', sigunguCode: '3' },
  '과천시': { areaCode: '31', sigunguCode: '3' },
  '경기도 광명시': { areaCode: '31', sigunguCode: '4' },
  '광명시': { areaCode: '31', sigunguCode: '4' },
  '경기도 광주시': { areaCode: '31', sigunguCode: '5' },
  '광주시': { areaCode: '31', sigunguCode: '5' },
  '경기도 구리시': { areaCode: '31', sigunguCode: '6' },
  '구리시': { areaCode: '31', sigunguCode: '6' },
  '경기도 군포시': { areaCode: '31', sigunguCode: '7' },
  '군포시': { areaCode: '31', sigunguCode: '7' },
  '경기도 김포시': { areaCode: '31', sigunguCode: '8' },
  '김포시': { areaCode: '31', sigunguCode: '8' },
  '경기도 남양주시': { areaCode: '31', sigunguCode: '9' },
  '남양주시': { areaCode: '31', sigunguCode: '9' },
  '경기도 동두천시': { areaCode: '31', sigunguCode: '10' },
  '동두천시': { areaCode: '31', sigunguCode: '10' },
  '경기도 부천시': { areaCode: '31', sigunguCode: '11' },
  '부천시': { areaCode: '31', sigunguCode: '11' },
  '경기도 성남시': { areaCode: '31', sigunguCode: '12' },
  '성남시': { areaCode: '31', sigunguCode: '12' },
  '경기도 수원시': { areaCode: '31', sigunguCode: '13' },
  '수원시': { areaCode: '31', sigunguCode: '13' },
  '경기도 시흥시': { areaCode: '31', sigunguCode: '14' },
  '시흥시': { areaCode: '31', sigunguCode: '14' },
  '경기도 안산시': { areaCode: '31', sigunguCode: '15' },
  '안산시': { areaCode: '31', sigunguCode: '15' },
  '경기도 안성시': { areaCode: '31', sigunguCode: '16' },
  '안성시': { areaCode: '31', sigunguCode: '16' },
  '경기도 안양시': { areaCode: '31', sigunguCode: '17' },
  '안양시': { areaCode: '31', sigunguCode: '17' },
  '경기도 양주시': { areaCode: '31', sigunguCode: '18' },
  '양주시': { areaCode: '31', sigunguCode: '18' },
  '경기도 양평군': { areaCode: '31', sigunguCode: '19' },
  '양평군': { areaCode: '31', sigunguCode: '19' },
  '경기도 여주시': { areaCode: '31', sigunguCode: '20' },
  '여주시': { areaCode: '31', sigunguCode: '20' },
  '경기도 연천군': { areaCode: '31', sigunguCode: '21' },
  '연천군': { areaCode: '31', sigunguCode: '21' },
  '경기도 오산시': { areaCode: '31', sigunguCode: '22' },
  '오산시': { areaCode: '31', sigunguCode: '22' },
  '경기도 용인시': { areaCode: '31', sigunguCode: '23' },
  '용인시': { areaCode: '31', sigunguCode: '23' },
  '경기도 의왕시': { areaCode: '31', sigunguCode: '24' },
  '의왕시': { areaCode: '31', sigunguCode: '24' },
  '경기도 의정부시': { areaCode: '31', sigunguCode: '25' },
  '의정부시': { areaCode: '31', sigunguCode: '25' },
  '경기도 이천시': { areaCode: '31', sigunguCode: '26' },
  '이천시': { areaCode: '31', sigunguCode: '26' },
  '경기도 파주시': { areaCode: '31', sigunguCode: '27' },
  '파주시': { areaCode: '31', sigunguCode: '27' },
  '경기도 평택시': { areaCode: '31', sigunguCode: '28' },
  '평택시': { areaCode: '31', sigunguCode: '28' },
  '경기도 포천시': { areaCode: '31', sigunguCode: '29' },
  '포천시': { areaCode: '31', sigunguCode: '29' },
  '경기도 하남시': { areaCode: '31', sigunguCode: '30' },
  '하남시': { areaCode: '31', sigunguCode: '30' },
  '경기도 화성시': { areaCode: '31', sigunguCode: '31' },
  '화성시': { areaCode: '31', sigunguCode: '31' },
  '경기도 강화군': { areaCode: '31', sigunguCode: '32' },
  '강화군': { areaCode: '31', sigunguCode: '32' },

  // ===== 강원특별자치도 (32) =====
  '강원특별자치도': { areaCode: '32' },
  '강원도': { areaCode: '32' },
  '강원': { areaCode: '32' },
  '강원특별자치도 강릉시': { areaCode: '32', sigunguCode: '1' },
  '강릉시': { areaCode: '32', sigunguCode: '1' },
  '강원특별자치도 고성군': { areaCode: '32', sigunguCode: '2' },
  '고성군': { areaCode: '32', sigunguCode: '2' },
  '강원특별자치도 동해시': { areaCode: '32', sigunguCode: '3' },
  '동해시': { areaCode: '32', sigunguCode: '3' },
  '강원특별자치도 삼척시': { areaCode: '32', sigunguCode: '4' },
  '삼척시': { areaCode: '32', sigunguCode: '4' },
  '강원특별자치도 속초시': { areaCode: '32', sigunguCode: '5' },
  '속초시': { areaCode: '32', sigunguCode: '5' },
  '강원특별자치도 양구군': { areaCode: '32', sigunguCode: '6' },
  '양구군': { areaCode: '32', sigunguCode: '6' },
  '강원특별자치도 양양군': { areaCode: '32', sigunguCode: '7' },
  '양양군': { areaCode: '32', sigunguCode: '7' },
  '강원특별자치도 영월군': { areaCode: '32', sigunguCode: '8' },
  '영월군': { areaCode: '32', sigunguCode: '8' },
  '강원특별자치도 원주시': { areaCode: '32', sigunguCode: '9' },
  '원주시': { areaCode: '32', sigunguCode: '9' },
  '강원특별자치도 인제군': { areaCode: '32', sigunguCode: '10' },
  '인제군': { areaCode: '32', sigunguCode: '10' },
  '강원특별자치도 정선군': { areaCode: '32', sigunguCode: '11' },
  '정선군': { areaCode: '32', sigunguCode: '11' },
  '강원특별자치도 철원군': { areaCode: '32', sigunguCode: '12' },
  '철원군': { areaCode: '32', sigunguCode: '12' },
  '강원특별자치도 춘천시': { areaCode: '32', sigunguCode: '13' },
  '춘천시': { areaCode: '32', sigunguCode: '13' },
  '강원특별자치도 태백시': { areaCode: '32', sigunguCode: '14' },
  '태백시': { areaCode: '32', sigunguCode: '14' },
  '강원특별자치도 평창군': { areaCode: '32', sigunguCode: '15' },
  '평창군': { areaCode: '32', sigunguCode: '15' },
  '강원특별자치도 홍천군': { areaCode: '32', sigunguCode: '16' },
  '홍천군': { areaCode: '32', sigunguCode: '16' },
  '강원특별자치도 화천군': { areaCode: '32', sigunguCode: '17' },
  '화천군': { areaCode: '32', sigunguCode: '17' },
  '강원특별자치도 횡성군': { areaCode: '32', sigunguCode: '18' },
  '횡성군': { areaCode: '32', sigunguCode: '18' },

  // ===== 충청북도 (33) =====
  '충청북도': { areaCode: '33' },
  '충북': { areaCode: '33' },
  '충청북도 괴산군': { areaCode: '33', sigunguCode: '1' },
  '괴산군': { areaCode: '33', sigunguCode: '1' },
  '충청북도 단양군': { areaCode: '33', sigunguCode: '2' },
  '단양군': { areaCode: '33', sigunguCode: '2' },
  '충청북도 보은군': { areaCode: '33', sigunguCode: '3' },
  '보은군': { areaCode: '33', sigunguCode: '3' },
  '충청북도 영동군': { areaCode: '33', sigunguCode: '4' },
  '영동군': { areaCode: '33', sigunguCode: '4' },
  '충청북도 옥천군': { areaCode: '33', sigunguCode: '5' },
  '옥천군': { areaCode: '33', sigunguCode: '5' },
  '충청북도 음성군': { areaCode: '33', sigunguCode: '6' },
  '음성군': { areaCode: '33', sigunguCode: '6' },
  '충청북도 제천시': { areaCode: '33', sigunguCode: '7' },
  '제천시': { areaCode: '33', sigunguCode: '7' },
  '충청북도 증평군': { areaCode: '33', sigunguCode: '8' },
  '증평군': { areaCode: '33', sigunguCode: '8' },
  '충청북도 진천군': { areaCode: '33', sigunguCode: '9' },
  '진천군': { areaCode: '33', sigunguCode: '9' },
  '충청북도 청주시': { areaCode: '33', sigunguCode: '10' },
  '청주시': { areaCode: '33', sigunguCode: '10' },
  '충청북도 충주시': { areaCode: '33', sigunguCode: '11' },
  '충주시': { areaCode: '33', sigunguCode: '11' },

  // ===== 충청남도 (34) =====
  '충청남도': { areaCode: '34' },
  '충남': { areaCode: '34' },
  '충청남도 계룡시': { areaCode: '34', sigunguCode: '1' },
  '계룡시': { areaCode: '34', sigunguCode: '1' },
  '충청남도 공주시': { areaCode: '34', sigunguCode: '2' },
  '공주시': { areaCode: '34', sigunguCode: '2' },
  '충청남도 금산군': { areaCode: '34', sigunguCode: '3' },
  '금산군': { areaCode: '34', sigunguCode: '3' },
  '충청남도 논산시': { areaCode: '34', sigunguCode: '4' },
  '논산시': { areaCode: '34', sigunguCode: '4' },
  '충청남도 당진시': { areaCode: '34', sigunguCode: '5' },
  '당진시': { areaCode: '34', sigunguCode: '5' },
  '충청남도 보령시': { areaCode: '34', sigunguCode: '6' },
  '보령시': { areaCode: '34', sigunguCode: '6' },
  '충청남도 부여군': { areaCode: '34', sigunguCode: '7' },
  '부여군': { areaCode: '34', sigunguCode: '7' },
  '충청남도 서산시': { areaCode: '34', sigunguCode: '8' },
  '서산시': { areaCode: '34', sigunguCode: '8' },
  '충청남도 서천군': { areaCode: '34', sigunguCode: '9' },
  '서천군': { areaCode: '34', sigunguCode: '9' },
  '충청남도 아산시': { areaCode: '34', sigunguCode: '10' },
  '아산시': { areaCode: '34', sigunguCode: '10' },
  '충청남도 예산군': { areaCode: '34', sigunguCode: '11' },
  '예산군': { areaCode: '34', sigunguCode: '11' },
  '충청남도 천안시': { areaCode: '34', sigunguCode: '12' },
  '천안시': { areaCode: '34', sigunguCode: '12' },
  '충청남도 청양군': { areaCode: '34', sigunguCode: '13' },
  '청양군': { areaCode: '34', sigunguCode: '13' },
  '충청남도 태안군': { areaCode: '34', sigunguCode: '14' },
  '태안군': { areaCode: '34', sigunguCode: '14' },
  '충청남도 홍성군': { areaCode: '34', sigunguCode: '15' },
  '홍성군': { areaCode: '34', sigunguCode: '15' },

  // ===== 경상북도 (35) =====
  '경상북도': { areaCode: '35' },
  '경북': { areaCode: '35' },
  '경상북도 경산시': { areaCode: '35', sigunguCode: '1' },
  '경산시': { areaCode: '35', sigunguCode: '1' },
  '경상북도 경주시': { areaCode: '35', sigunguCode: '2' },
  '경주시': { areaCode: '35', sigunguCode: '2' },
  '경상북도 고령군': { areaCode: '35', sigunguCode: '3' },
  '고령군': { areaCode: '35', sigunguCode: '3' },
  '경상북도 구미시': { areaCode: '35', sigunguCode: '4' },
  '구미시': { areaCode: '35', sigunguCode: '4' },
  '경상북도 김천시': { areaCode: '35', sigunguCode: '5' },
  '김천시': { areaCode: '35', sigunguCode: '5' },
  '경상북도 문경시': { areaCode: '35', sigunguCode: '6' },
  '문경시': { areaCode: '35', sigunguCode: '6' },
  '경상북도 봉화군': { areaCode: '35', sigunguCode: '7' },
  '봉화군': { areaCode: '35', sigunguCode: '7' },
  '경상북도 상주시': { areaCode: '35', sigunguCode: '8' },
  '상주시': { areaCode: '35', sigunguCode: '8' },
  '경상북도 성주군': { areaCode: '35', sigunguCode: '9' },
  '성주군': { areaCode: '35', sigunguCode: '9' },
  '경상북도 안동시': { areaCode: '35', sigunguCode: '10' },
  '안동시': { areaCode: '35', sigunguCode: '10' },
  '경상북도 영덕군': { areaCode: '35', sigunguCode: '11' },
  '영덕군': { areaCode: '35', sigunguCode: '11' },
  '경상북도 영양군': { areaCode: '35', sigunguCode: '12' },
  '영양군': { areaCode: '35', sigunguCode: '12' },
  '경상북도 영주시': { areaCode: '35', sigunguCode: '13' },
  '영주시': { areaCode: '35', sigunguCode: '13' },
  '경상북도 영천시': { areaCode: '35', sigunguCode: '14' },
  '영천시': { areaCode: '35', sigunguCode: '14' },
  '경상북도 예천군': { areaCode: '35', sigunguCode: '15' },
  '예천군': { areaCode: '35', sigunguCode: '15' },
  '경상북도 울릉군': { areaCode: '35', sigunguCode: '16' },
  '울릉군': { areaCode: '35', sigunguCode: '16' },
  '경상북도 울진군': { areaCode: '35', sigunguCode: '17' },
  '울진군': { areaCode: '35', sigunguCode: '17' },
  '경상북도 의성군': { areaCode: '35', sigunguCode: '18' },
  '의성군': { areaCode: '35', sigunguCode: '18' },
  '경상북도 청도군': { areaCode: '35', sigunguCode: '19' },
  '청도군': { areaCode: '35', sigunguCode: '19' },
  '경상북도 청송군': { areaCode: '35', sigunguCode: '20' },
  '청송군': { areaCode: '35', sigunguCode: '20' },
  '경상북도 칠곡군': { areaCode: '35', sigunguCode: '21' },
  '칠곡군': { areaCode: '35', sigunguCode: '21' },
  '경상북도 포항시': { areaCode: '35', sigunguCode: '22' },
  '포항시': { areaCode: '35', sigunguCode: '22' },

  // ===== 경상남도 (36) =====
  '경상남도': { areaCode: '36' },
  '경남': { areaCode: '36' },
  '경상남도 거제시': { areaCode: '36', sigunguCode: '1' },
  '거제시': { areaCode: '36', sigunguCode: '1' },
  '경상남도 거창군': { areaCode: '36', sigunguCode: '2' },
  '거창군': { areaCode: '36', sigunguCode: '2' },
  '경상남도 고성군': { areaCode: '36', sigunguCode: '3' },
  '경상남도 김해시': { areaCode: '36', sigunguCode: '4' },
  '김해시': { areaCode: '36', sigunguCode: '4' },
  '경상남도 남해군': { areaCode: '36', sigunguCode: '5' },
  '남해군': { areaCode: '36', sigunguCode: '5' },
  '경상남도 밀양시': { areaCode: '36', sigunguCode: '6' },
  '밀양시': { areaCode: '36', sigunguCode: '6' },
  '경상남도 사천시': { areaCode: '36', sigunguCode: '7' },
  '사천시': { areaCode: '36', sigunguCode: '7' },
  '경상남도 산청군': { areaCode: '36', sigunguCode: '8' },
  '산청군': { areaCode: '36', sigunguCode: '8' },
  '경상남도 양산시': { areaCode: '36', sigunguCode: '9' },
  '양산시': { areaCode: '36', sigunguCode: '9' },
  '경상남도 의령군': { areaCode: '36', sigunguCode: '10' },
  '의령군': { areaCode: '36', sigunguCode: '10' },
  '경상남도 진주시': { areaCode: '36', sigunguCode: '11' },
  '진주시': { areaCode: '36', sigunguCode: '11' },
  '경상남도 창녕군': { areaCode: '36', sigunguCode: '12' },
  '창녕군': { areaCode: '36', sigunguCode: '12' },
  '경상남도 창원시': { areaCode: '36', sigunguCode: '13' },
  '창원시': { areaCode: '36', sigunguCode: '13' },
  '경상남도 통영시': { areaCode: '36', sigunguCode: '14' },
  '통영시': { areaCode: '36', sigunguCode: '14' },
  '경상남도 하동군': { areaCode: '36', sigunguCode: '15' },
  '하동군': { areaCode: '36', sigunguCode: '15' },
  '경상남도 함안군': { areaCode: '36', sigunguCode: '16' },
  '함안군': { areaCode: '36', sigunguCode: '16' },
  '경상남도 함양군': { areaCode: '36', sigunguCode: '17' },
  '함양군': { areaCode: '36', sigunguCode: '17' },
  '경상남도 합천군': { areaCode: '36', sigunguCode: '18' },
  '합천군': { areaCode: '36', sigunguCode: '18' },

  // ===== 전북특별자치도 (37) =====
  '전북특별자치도': { areaCode: '37' },
  '전라북도': { areaCode: '37' },
  '전북': { areaCode: '37' },
  '전북특별자치도 고창군': { areaCode: '37', sigunguCode: '1' },
  '고창군': { areaCode: '37', sigunguCode: '1' },
  '전북특별자치도 군산시': { areaCode: '37', sigunguCode: '2' },
  '군산시': { areaCode: '37', sigunguCode: '2' },
  '전북특별자치도 김제시': { areaCode: '37', sigunguCode: '3' },
  '김제시': { areaCode: '37', sigunguCode: '3' },
  '전북특별자치도 남원시': { areaCode: '37', sigunguCode: '4' },
  '남원시': { areaCode: '37', sigunguCode: '4' },
  '전북특별자치도 무주군': { areaCode: '37', sigunguCode: '5' },
  '무주군': { areaCode: '37', sigunguCode: '5' },
  '전북특별자치도 부안군': { areaCode: '37', sigunguCode: '6' },
  '부안군': { areaCode: '37', sigunguCode: '6' },
  '전북특별자치도 순창군': { areaCode: '37', sigunguCode: '7' },
  '순창군': { areaCode: '37', sigunguCode: '7' },
  '전북특별자치도 완주군': { areaCode: '37', sigunguCode: '8' },
  '완주군': { areaCode: '37', sigunguCode: '8' },
  '전북특별자치도 익산시': { areaCode: '37', sigunguCode: '9' },
  '익산시': { areaCode: '37', sigunguCode: '9' },
  '전북특별자치도 임실군': { areaCode: '37', sigunguCode: '10' },
  '임실군': { areaCode: '37', sigunguCode: '10' },
  '전북특별자치도 장수군': { areaCode: '37', sigunguCode: '11' },
  '장수군': { areaCode: '37', sigunguCode: '11' },
  '전북특별자치도 전주시': { areaCode: '37', sigunguCode: '12' },
  '전주시': { areaCode: '37', sigunguCode: '12' },
  '전북특별자치도 정읍시': { areaCode: '37', sigunguCode: '13' },
  '정읍시': { areaCode: '37', sigunguCode: '13' },
  '전북특별자치도 진안군': { areaCode: '37', sigunguCode: '14' },
  '진안군': { areaCode: '37', sigunguCode: '14' },

  // ===== 전라남도 (38) =====
  '전라남도': { areaCode: '38' },
  '전남': { areaCode: '38' },
  '전라남도 강진군': { areaCode: '38', sigunguCode: '1' },
  '강진군': { areaCode: '38', sigunguCode: '1' },
  '전라남도 고흥군': { areaCode: '38', sigunguCode: '2' },
  '고흥군': { areaCode: '38', sigunguCode: '2' },
  '전라남도 곡성군': { areaCode: '38', sigunguCode: '3' },
  '곡성군': { areaCode: '38', sigunguCode: '3' },
  '전라남도 광양시': { areaCode: '38', sigunguCode: '4' },
  '광양시': { areaCode: '38', sigunguCode: '4' },
  '전라남도 구례군': { areaCode: '38', sigunguCode: '5' },
  '구례군': { areaCode: '38', sigunguCode: '5' },
  '전라남도 나주시': { areaCode: '38', sigunguCode: '6' },
  '나주시': { areaCode: '38', sigunguCode: '6' },
  '전라남도 담양군': { areaCode: '38', sigunguCode: '7' },
  '담양군': { areaCode: '38', sigunguCode: '7' },
  '전라남도 목포시': { areaCode: '38', sigunguCode: '8' },
  '목포시': { areaCode: '38', sigunguCode: '8' },
  '전라남도 무안군': { areaCode: '38', sigunguCode: '9' },
  '무안군': { areaCode: '38', sigunguCode: '9' },
  '전라남도 보성군': { areaCode: '38', sigunguCode: '10' },
  '보성군': { areaCode: '38', sigunguCode: '10' },
  '전라남도 순천시': { areaCode: '38', sigunguCode: '11' },
  '순천시': { areaCode: '38', sigunguCode: '11' },
  '전라남도 신안군': { areaCode: '38', sigunguCode: '12' },
  '신안군': { areaCode: '38', sigunguCode: '12' },
  '전라남도 여수시': { areaCode: '38', sigunguCode: '13' },
  '여수시': { areaCode: '38', sigunguCode: '13' },
  '전라남도 영광군': { areaCode: '38', sigunguCode: '14' },
  '영광군': { areaCode: '38', sigunguCode: '14' },
  '전라남도 영암군': { areaCode: '38', sigunguCode: '15' },
  '영암군': { areaCode: '38', sigunguCode: '15' },
  '전라남도 완도군': { areaCode: '38', sigunguCode: '16' },
  '완도군': { areaCode: '38', sigunguCode: '16' },
  '전라남도 장성군': { areaCode: '38', sigunguCode: '17' },
  '장성군': { areaCode: '38', sigunguCode: '17' },
  '전라남도 장흥군': { areaCode: '38', sigunguCode: '18' },
  '장흥군': { areaCode: '38', sigunguCode: '18' },
  '전라남도 진도군': { areaCode: '38', sigunguCode: '19' },
  '진도군': { areaCode: '38', sigunguCode: '19' },
  '전라남도 함평군': { areaCode: '38', sigunguCode: '20' },
  '함평군': { areaCode: '38', sigunguCode: '20' },
  '전라남도 해남군': { areaCode: '38', sigunguCode: '21' },
  '해남군': { areaCode: '38', sigunguCode: '21' },
  '전라남도 화순군': { areaCode: '38', sigunguCode: '22' },
  '화순군': { areaCode: '38', sigunguCode: '22' },

  // ===== 제주특별자치도 (39) =====
  '제주특별자치도': { areaCode: '39' },
  '제주도': { areaCode: '39' },
  '제주': { areaCode: '39' },
  '제주특별자치도 서귀포시': { areaCode: '39', sigunguCode: '1' },
  '서귀포시': { areaCode: '39', sigunguCode: '1' },
  '제주특별자치도 제주시': { areaCode: '39', sigunguCode: '2' },
  '제주시': { areaCode: '39', sigunguCode: '2' },
};

/**
 * 지역명으로 지역 코드 찾기
 * 유연한 매칭을 지원 (띄어쓰기 제거, 접미사 제거 등)
 */
export function findAreaCode(regionName: string): AreaCode | null {
  // 1. 정확한 매칭 시도
  if (KOREA_AREA_CODES[regionName]) {
    return KOREA_AREA_CODES[regionName];
  }

  // 2. 공백을 포함한 버전 시도
  const withProvince = `${regionName.split(' ')[0]} ${regionName.split(' ').slice(1).join(' ')}`;
  if (KOREA_AREA_CODES[withProvince]) {
    return KOREA_AREA_CODES[withProvince];
  }

  // 3. 시/군/구 접미사 제거하고 시도
  const cleaned = regionName.replace(/(시|군|구)$/, '');
  for (const [key, value] of Object.entries(KOREA_AREA_CODES)) {
    if (key.includes(cleaned)) {
      return value;
    }
  }

  return null;
}
